<div style="padding: 0 20px;">
	<div class="form formGroup showForm">
		<p class="h2">Informacje o kliencie</p>
		<div class="row">
			<label>ID: </label>
			<span class="textLine"><?= $this->data['id']; ?></span>
		</div>
		<div class="row">
			<label>Imię i nazwisko: </label>
			<span class="textLine"><?= $this->data['nazw']; ?></span>
		</div>
		<div class="row">
			<label>Adres zameldowania: </label>
			<span class="textLine"><?= $this->data['adr_zameld']; ?></span>
		</div>
		<div class="row">
			<label>Numer telefonu: </label>
			<span class="textLine"><?= $this->data['nr_tel']; ?></span>
		</div>
		<div class="row">
			<label>Adres e-mail: </label>
			<span class="textLine"><?= $this->data['mail']; ?></span>
		</div>
		<div class="row">
			<label>Wariant posiadanego ubezpieczenia: </label>
			<span class="textLine"><?= $this->data['war_ubez']; ?></span>
		</div>
		<div class="row">
			<label>Login: </label>
			<span class="textLine"><?= $this->data['login']; ?></span>
		</div>
	</div>
</div>