<div class="objectMenu tableObjectMenu">
	<div class="row">
		<div class="icon"></div>
		<div class="text"><a href="<?= $this->directoryUrl.'/zarzadzanieklientem/showcustomer/clientid/'.$this->customer['id']; ?>">Pokaż więcej informacji</a></div>
	</div>
	<div class="row">
		<div class="icon"></div>
		<div class="text"><a href="<?= $this->directoryUrl.'/zarzadzanieklientem/editcustomer/clientid/'.$this->customer['id']; ?>">Edytuj dane osobowe</a></div>
	</div>
	<div class="row">
		<div class="icon"></div>
		<div class="text"><a href="<?= $this->directoryUrl.'/zarzadzanieklientem/newcar/clientid/'.$this->customer['id']; ?>">Dodaj samochód</a></div>
	</div>
	<div class="row">
		<div class="icon" style="margin-top: 2px"><img src="<?= $this->baseUrl.'/public/template/img/admin/remove-blog-hover-icon.png'; ?>"/></div> 
		<div class="text"><a href="<?= $this->directoryUrl.'/zarzadzanieklientem/delcustomer/clientid/'.$this->customer['id']; ?>">Usuń klienta</a></div>
	</div>
</div>