<div style="padding: 20px">
	<form action="<?= $this->directoryUrl.'/zarzadzanieklientem/newcustomer/type/noContent'; ?>" method="POST" class="form saveBoxOn settingsForm">
		<p class="h2">Nowy klient</p>
		<div class="group">
			<div class="row">
				<label>Nazwa / Imię i nazwisko <span class="small">nazwa firmy lub imię i nazwisko klienta</span></label>
				<input type="text" name="dane[nazw]">
			</div>
			<div class="row">
				<label>NIP/PESEL </label>
				<input type="text" name="dane[nip]">
			</div>
			<div class="row">
				<label>Adres </label>
				<input type="text" name="dane[adres]" placeholder="np. Miejscowość XX-XXX, Ulica D/M">
			</div>
			<div class="row">
				<label>Numer telefonu </label>
				<input type="text" name="dane[tel]" placeholder="xxx-xxx-xxx">
			</div>
			<div class="row">
				<label>Adres e-mail </label>
				<input type="text" name="dane[email]" placeholder="xxxxx@xxxx.xx">
			</div>
			<div class="row">
				<label>Wariant posiadanego ubezpieczenia </label>
				<input type="text" name="dane[warub]">
			</div>
		</div>

		<div class="group">
			<div class="row">
				<label>Login <span class="small">Max 25 znaków</span></label>
				<input type="text" name="dane[login]" placeholder="login">
			</div>
			<div class="row">
				<label>Hasło <span class="small">Maks 25 znaków</span></label>
				<input type="password" name="dane[haslo]" placeholder="hasło">
			</div>
		</div>
	</form>
</div>