<div style="padding: 0 20px;">
	<div class="form formGroup showForm">
		<p class="h2">Informacje o samochodzie</p>
		<div class="row">
			<label>ID: </label>
			<span class="textLine"><?= $this->data['id']; ?></span>
		</div>
		<div class="row">
			<label>Marka: </label>
			<span class="textLine"><?= $this->data['Marka']; ?></span>
		</div>
		<div class="row">
			<label>Model: </label>
			<span class="textLine"><?= $this->data['Model']; ?></span>
		</div>
		<div class="row">
			<label>Rok produkcji </label>
			<span class="textLine"><?= $this->data['Rok_pr']; ?></span>
		</div>
		<div class="row">
			<label>Przebieg: </label>
			<span class="textLine"><?= $this->data['Przeb']; ?></span>
		</div>
		<div class="row">
			<label>Wersja wyposażenia: </label>
			<span class="textLine"><?= $this->data['Wer_wyp']; ?></span>
		</div>
		<div class="row">
			<label>Rodzaj nadwozia: </label>
			<span class="textLine"><?= $this->data['Rodz_nadw']; ?></span>
		</div>
		<div class="row">
			<label>Pojemność silnika: </label>
			<span class="textLine"><?= $this->data['poj_sil']; ?></span>
		</div>
		<div class="row">
			<label>Moc silnika: </label>
			<span class="textLine"><?= $this->data['Moc_sil']; ?></span>
		</div>
		<div class="row">
			<label>Rodzaj silnika: </label>
			<span class="textLine"><?= $this->data['Rodz_sil']; ?></span>
		</div>
		<div class="row">
			<label>Rodzaj oleju silnikowego: </label>
			<span class="textLine"><?= $this->data['rodz_ol_sil']; ?></span>
		</div>
		<div class="row">
			<label>Napęd: </label>
			<span class="textLine"><?= $this->data['Naped']; ?></span>
		</div>
	</div>
</div>