ID: <?php echo $this->data['id'];?><br/>
Model: <?php echo $this->data['Model'];?><br/>
Marka: <?php echo $this->data['Marka'];?><br/>
Rok produkcji: <?php echo $this->data['Rok_pr'];?><br/>
Przebieg: <?php echo $this->data['Przeb'];?><br/>
Wersja wyposażenia: <?php echo $this->data['wer_wyp'];?><br/>
Rodzaj nadwozia: <?php echo $this->data['Rodz_nadw'];?><br/>
Pojmność silnika: <?php echo $this->data['poj_sil'];?><br/>
Moc silnika: <?php echo $this->data['Moc_sil'];?><br/>
Rodzaj silnika: <?php echo $this->data['Rodz_sil'];?><br/>
Rodzaj oleju silnikowego: <?php echo $this->data['rodz_ol_sil'];?><br/>
Napęd: <?php echo $this->data['Naped'];?><br/>
