ID <?php echo $this->data['id'];?> <br/>
Nazwa / Imie i nazwisko <?php echo $this->data['nazw'];?> <br/>
NIP/PESEL <?php echo $this->data['nip_pesel'];?> <br/>
Adres zameldowania <?php echo $this->data['adr_zameld'];?> <br/>
Numer telefonu <?php echo $this->data['nr_tel'];?> <br/>
Adres e-mail <?php echo $this->data['mail'];?> <br/>
Wariant posiadanego ubezpieczenia <?php echo $this->data['war_ubez'];?> <br/>
Login <?php echo $this->data['login'];?> <br/>
