<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">  
<head><?= $this->renderContent("const/head.phtml"); ?></head>                                        
<body>

	<div class="top" style="color: black">Panel zarządzania zakładem mechanicznym</div>

	<?= $this->renderContent("const/errorBox.phtml"); ?>

	<div id="page">
		<div class="pageText">
			<?= $this->getContent(); ?>
		</div>
	</div>

</body>
</html>