<?php	
	if(isset($_SESSION[$this->_config->dbTableNames->Pracownik]["msg"]["text"]) && !empty($_SESSION[$this->_config->dbTableNames->Pracownik]["msg"]["text"])) {
		if($this->_getParam('type')=='msg') { 
			$state = $_SESSION[$this->_config->dbTableNames->Pracownik]['msg']['state'];
			$text = $_SESSION[$this->_config->dbTableNames->Pracownik]['msg']['text'];
			if(isset($_SESSION[$this->_config->dbTableNames->Pracownik]['msg']['state'])) unset($_SESSION[$this->_config->dbTableNames->Pracownik]['msg']); 
		}
	}
	
	echo '<div id="errorBox" class="'.$state.'">'.$text.'</div>';
?>