<div id="bg" class="heighter">
	<div class="formLogin">
		<div class="form">                  
			<form action="<?= $this->directoryUrl; ?>/index/login/type/msg" method="POST">
				<div class="row">
					<label class="blackBg">LOGIN: </label>
					<input type="text" name="login">
				</div>
				<div class="row">
					<label class="blackBg">HASŁO: </label>
					<input type="password" name="pass">
				</div>
				<div class="row">
					<input type="submit" class="submit logIn" name="checkLoginData" value="zaloguj">
				</div>
			</form>
		</div>
	</div>
</div>