<div class="objectMenu tableObjectMenu">
	<div class="row">
		<div class="icon"></div>
		<div class="text"><a href="<?= $this->directoryUrl.'/zarzadzaniezadaniami/getdetails/repairid/'.$this->repair['id']; ?>">Pokaż więcej informacji</a></div>
	</div>
	<div class="row">
		<div class="icon"></div>
		<div class="text"><a href="<?= $this->directoryUrl.'/zarzadzaniezadaniami/editrepair/repairid/'.$this->repair['id']; ?>">Edytuj</a></div>
	</div>
</div>