<div style="padding: 20px">
	<form action="<?= $this->directoryUrl.'/zarzadzanieobslugakli/editservice/serviceid/'.$this->service['id'].'/type/noContent/'; ?>" method="POST" class="form saveBoxOn settingsForm">
		<p class="h2">Edytuj dane pracownika</p>
		<div class="group">
			<div class="row">
				<label>Imię </label>
                                <input type="text" name="dane[imie]" value="<?php echo $this->service['Imie'];?>">
			</div>
                    <div class="row">
				<label>Nazwisko </label>
                                <input type="text" name="dane[nazw]" value="<?php echo $this->service['Nazw'];?>">
			</div>
			<div class="row">
				<label>PESEL </label>
				<input type="text" name="dane[pesel]" value="<?php echo $this->service['pesel'];?>">
			</div>
			<div class="row">
				<label>Adres </label>
				<input type="text" name="dane[adres]" value="<?php echo $this->service['adr_zam'];?>">
			</div>
			<div class="row">
				<label>Numer telefonu </label>
				<input type="text" name="dane[tel]" value="<?php echo $this->service['nr_tel'];?>">
			</div>
			<div class="row">
				<label>Adres e-mail </label>
				<input type="text" name="dane[email]" value="<?php echo $this->service['mail'];?>">
			</div>
			<div class="row">
				<label>Specjalizacja </label>
				<input type="text" name="dane[spe]" value="<?php echo $this->service['specj'];?>">
			</div>
                    <div class="row">
				<label>Doświadczenie zawodowe </label>
				<input type="text" name="dane[dosw]" value="<?php echo $this->service['dosw_zaw'];?>">
			</div>
                    <div class="row">
				<label>Dyspozycyjność </label>
				<input type="text" name="dane[dysp]" value="<?php echo $this->service['dyspoz'];?>">
			</div>
                    <div class="row">
				<label>Obsługiwane stanowiska </label>
				<input type="text" name="dane[stan]" value="<?php echo $this->service['obsl_stan'];?>">
			</div>
		</div>

		<div class="group">
			<div class="row">
				<label>Login <span class="small">Max 25 znaków</span></label>
				<input type="text" name="dane[login]" value="<?php echo $this->service['login'];?>">
			</div>
			<div class="row">
				<label>Hasło <span class="small">Maks 25 znaków</span></label>
				<input type="password" name="dane[haslo]" placeholder="hasło">
                                    
			</div>
                    <input type="submit" value="Zapisz">
		</div>
	</form>
</div>