<div class="objectMenu tableObjectMenu">
	<div class="row">
		<div class="icon"></div>
		<div class="text"><a href="<?= $this->directoryUrl.'/zarzadzaniestanowiskami/showplace/placeid/'.$this->place['id']; ?>">Pokaż więcej informacji</a></div>
	</div>
	<div class="row">
		<div class="icon"></div>
		<div class="text"><a href="<?= $this->directoryUrl.'/zarzadzaniestanowiskami/editplace/placeid/'.$this->place['id']; ?>">Edytuj stanowisko</a></div>
	</div>
	<div class="row">
		<div class="icon" style="margin-top: 2px"><img src="<?= $this->baseUrl.'/public/template/img/admin/remove-blog-hover-icon.png'; ?>"/></div> 
		<div class="text"><a href="<?= $this->directoryUrl.'/zarzadzaniestanowiskami/delplace/placeid/'.$this->place['id'].'/type/noContent/'; ?>">Usuń mechanika</a></div>
	</div>
</div>