<div style="padding: 20px">
	<form action="<?= $this->directoryUrl.'/zarzadzaniestanowiskami/editplace/placeid/'.$this->place['id'].'/type/noContent/'; ?>" method="POST" class="form saveBoxOn settingsForm">
		<p class="h2">Nowe stanowisko</p>
		<div class="group">
			<div class="row">
				<label>Nazwa </label>
                                <input type="text" name="dane[Nazw]" value="<?php echo $this->place['Nazw'];?>" >
			</div>
                    <div class="row">
				<label>Ładowność </label>
                                <input type="text" name="dane[ladow]" value="<?php echo $this->place['ladow'];?>">
			</div>
			<div class="row">
				<label>Wymiary </label>
				<input type="text" name="dane[wymiary]" value="<?php echo $this->place['wymiary'];?>" >
			</div>
			<div class="row">
				<label>Posiada tunel </label>
                                <input type="checkbox" name="stat"  <?php echo ($this->place['Posiad_tun']== 'y') ? 'checked="checked"':'';?> value="y"> 
			</div>
			<div class="row">
				<label>Przeznaczenie </label>
				<input type="text" name="dane[przezn]"value="<?php echo $this->place['przezn'];?>">
			</div>
                    <input type="submit" value="Wyślij">
		</div>
	</form>
</div>