<div style="padding: 20px">
	<form action="<?= $this->directoryUrl.'/zarzadzaniestanowiskami/newplace/type/noContent/'; ?>" method="POST" class="form saveBoxOn settingsForm">
		<p class="h2">Nowe stanowisko</p>
		<div class="group">
			<div class="row">
				<label>Nazwa </label>
                                <input type="text" name="dane[nazwa]">
			</div>
                    <div class="row">
				<label>Ładowność </label>
                                <input type="text" name="dane[lad]">
			</div>
			<div class="row">
				<label>Wymiary </label>
				<input type="text" name="dane[wymiar]">
			</div>
			<div class="row">
				<label>Posiada tunel </label>
                                <input type="checkbox" name="stat" value="y"> 
			</div>
			<div class="row">
				<label>Przeznaczenie </label>
				<input type="text" name="dane[pr]">
			</div>
			
		</div>
	</form>
</div>