<div class="objectMenu tableObjectMenu">
	<div class="row">
		<div class="icon"></div>
		<div class="text"><a href="<?= $this->directoryUrl.'/mechanik/showrepair/repairid/'.$this->repair['id']; ?>">Pokaż więcej informacji</a></div>
	</div>
	<div class="row">
		<div class="icon"></div>
		<div class="text"><a href="<?= $this->directoryUrl.'/mechanik/editrepair/repairid/'.$this->repair['id']; ?>">Zmień status</a></div>
	</div>
    <div class="row">
		<div class="icon"></div>
		<div class="text"><a href="<?= $this->directoryUrl.'/mechanik/addparts/repairid/'.$this->repair['id']; ?>">Zamów częsci</a></div>
	</div>
</div>