<div id="menu">
	<ul class="firstLevel">
		<li class="<?= $this->_controllerName=='zarzadzanieklientem' ? 'active':''; ?>">
			<a><span class="title">Aktualne naprawy</span></a>
		</li>

		<li class="<?= $this->_controllerName=='mechanicy' ? 'active':''; ?>">
			<a><span class="title">Moje dane</span></a>
		</li>

		<li class="<?= $this->_controllerName=='stanowiska' ? 'active':''; ?>">
			<a><span class="title">Moje samochody</span></a>
		</li>
	</ul>
</div>