<div id="menu">
	<ul class="firstLevel">
		<li class="<?= $this->_controllerName=='zarzadzanieklientem' ? 'active':''; ?>">
			<a href="<?= $this->baseUrl.'/naprawa/index'; ?>"><span class="title">Aktualne naprawy</span></a>
		</li>

		<li class="<?= $this->_controllerName=='mechanicy' ? 'active':''; ?>">
			<a href="<?= $this->baseUrl.'/dane/index'; ?>"><span class="title">Moje dane</span></a>
		</li>

		<li class="<?= $this->_controllerName=='stanowiska' ? 'active':''; ?>">
			<a href="<?= $this->baseUrl.'/samochod/index'; ?>"><span class="title">Moje samochody</span></a>
		</li>
	</ul>
</div>