<div class="objectMenu tableObjectMenu">
	<div class="row">
		<div class="icon"></div>
		<div class="text"><a href="<?= $this->directoryUrl.'/zarzadzaniemechanikami/showmechanic/mechanicid/'.$this->mechanic['id']; ?>">Pokaż więcej informacji</a></div>
	</div>
	<div class="row">
		<div class="icon"></div>
		<div class="text"><a href="<?= $this->directoryUrl.'/zarzadzaniemechanikami/editmechanic/mechanicid/'.$this->mechanic['id']; ?>">Edytuj dane osobowe</a></div>
	</div>
	<div class="row">
		<div class="icon" style="margin-top: 2px"><img src="<?= $this->baseUrl.'/public/template/img/admin/remove-blog-hover-icon.png'; ?>"/></div> 
		<div class="text"><a href="<?= $this->directoryUrl.'/zarzadzaniemechanikami/delmechanic/mechanicid/'.$this->mechanic['id'].'/type/noContent/'; ?>">Usuń mechanika</a></div>
	</div>
</div>